fix: parse version from filesystem supplier correctly
dlang/dub pull request #2220
Opened 2022-02-14 19:37 UTC by Panke

2022-02-14 20:09 UTC, WebFreak001 requested changes
I think there should be some validation that the basename actually starts with the packageId here

2022-02-14 20:09 UTC, WebFreak001 commented on source/dub/packagesuppliers/filesystem.d
> +		json["version"] = basename[packageId.length + 1 .. $-4];
```suggestion
		enforce(basename.startsWith(packageId), "Malformed package file name " ~ filePath.toNativeString());
		json["version"] = basename[packageId.length + 1 .. $].stripExtension();
```

but you probably need to import std.exception here as well.

2022-02-15 07:27 UTC, Panke commented
Done

2022-02-15 07:50 UTC, WebFreak001 requested changes
last change request by me (also needs import)

2022-02-15 07:50 UTC, WebFreak001 commented on source/dub/packagesuppliers/filesystem.d
> +		enforce(basename[$-4..$] == ".zip", "Malformed package filename: " ~ filePath.toNativeString);
use endsWith for consistency pls (and to avoid potential range errors, though they cannot really occur now)

2022-02-15 09:36 UTC, Panke commented
Done, if the tests are still happy.

2022-02-15 09:55 UTC, WebFreak001 approved these changes

2022-02-15 10:20 UTC, merged