Read stuff once
dlang/dub pull request #2406
Opened 2022-08-18 13:26 UTC by nordlow

2022-08-18 14:00 UTC, nordlow commented
CI seems broken.

2022-08-18 14:00 UTC, nordlow commented
Ready for review now, @Geod24.

2022-08-18 14:58 UTC, nordlow commented
Changed to WIP. I just realized yet another optimization.

2022-08-18 14:58 UTC, nordlow commented on source/dub/packagemanager.d
> +					// Packages are stored in $ROOT/$NAME-$VERSION/`
Do we still need to support file structure, @Geod24?

2022-08-18 15:04 UTC, Geod24 commented
This I need to review from a computer, but reducing the number of scans shouldn't be the goal. Eliminating the scan all together is IMO the way to go.

2022-08-18 22:09 UTC, nordlow commented
Are CI failure unrelated?

2022-08-18 23:43 UTC, Geod24 commented
> Are CI failures unrelated?

Why would they be unrelated ?

2022-12-15 09:33 UTC, WebFreak001 requested changes
this includes non-trivial changes to source code, please rebase and remove the `[skip ci]`

2024-06-18 11:04 UTC, Geod24 commented
We now have a no-scan behavior, closing as stalled.

2024-06-18 11:04 UTC, closed without merging

2024-06-18 11:20 UTC, nordlow commented
> We now have a no-scan behavior, closing as stalled.

Awesome. Thanks.