Integrate `dependencyBuildSettings` into dependencies
dlang/dub pull request #2430
Opened 2022-08-24 04:44 UTC by Geod24

Because those are specified in `dependencies`,
they should be stored alongside them.
Unfortunately this will slihtly increase memory usage in the common case,
but unlikely to a point where it would be problematic.

This is technically a breaking change as a field is getting removed,
however this struct has been manipulated a few times in breaking ways,
and it's unlikely `dependencyBuildSettings` is being used outside of dub,
given how recent it is and how narrow its usage is.
However, as `dependencies` is likely to be widely used, a compatibility
type and an `alias this` are provided not to break client code.

2022-08-24 04:44 UTC, Geod24 commented
CC @omerfirmak ;)

2022-08-25 10:57 UTC, WebFreak001 requested changes
overall this is a nice improvement, can you make the RecipeDependency struct public? (or why don't we just put BuildSettingsTemplate inside Dependency?)

2022-08-25 11:25 UTC, Geod24 commented
Done

2022-08-25 12:48 UTC, WebFreak001 approved these changes

2022-08-25 12:51 UTC, merged