add --deep flag to `dub build`
dlang/dub pull request #2647
Opened 2023-05-25 20:00 UTC by rtbo

Allows to build all dependencies of a static library.

This provides the same functionality as the [dub-build-deep](https://code.dlang.org/packages/dub-build-deep) package.
The difference is that all dependencies are built in the same DUB invocation, which imply that the build will be fully compatible with `dub describe`.

E.g.
`dub describe vibe-d:http` will describe the build settings of all dependencies of `vibe-d:http` and `dub build --deep vibe-d:http` will build all dependencies with the exact same build settings.
If we build dependencies one by one (as done by `dub-build-deep`), some settings will differ.

See also #2644

Fixes #2224 (and possibly #2209)

2023-08-12 10:44 UTC, MrcSnm requested changes
@rtbo So far, the only thing I see missing is a test. Add a test using the --deep flag
I'm also really looking for that since I have been using quite a hack for my engine

2023-08-12 14:43 UTC, MrcSnm approved these changes
LGTM @WebFreak001 @Geod24

2023-08-13 13:24 UTC, MrcSnm commented
@rtbo I have wrote this file here:

```
Added `--deep=` switch to dub build

By specifying this flag, you can now build all the dependencies
of a staticLibrary. The default behavior is to only build the
library located in the root directory of the dub configuration
file. This allows better integration with other build systems
which require the libraries to be built upfront.

```
dub build --deep
```

If a staticLibrary A depends on staticLibrary B, and the --deep
flag is specified, dub will output both the A and B libraries.
```

Feel free to modify as you see fit. This is a required file which goes inside the changelog folder.

2023-08-16 18:55 UTC, MrcSnm commented
Hey there @WebFreak001 @Geod24 can you take a look into this PR?

2023-08-16 19:11 UTC, WebFreak001 approved these changes

2023-08-16 19:11 UTC, merged