fix segfault when no versions for a pacakge is found
dlang/dub pull request #2725
Opened 2023-12-14 11:37 UTC by gedaiu

fix #2724

2023-12-14 11:44 UTC, rikkimax requested changes

2023-12-14 11:44 UTC, rikkimax commented on source/dub/project.d
> +				if (!m_dependencies.canFind(p) && p !is null) {
```suggestion
				if (p !is null && !m_dependencies.canFind(p)) {
```

No need to do the canFind which will be ``O(1)`` if its null.

2023-12-17 19:05 UTC, Geod24 commented
Under what circumstances does the bug trigger ? Can you add a test ?

2023-12-18 22:54 UTC, gedaiu commented
Hey @Geod24, it happens with one of my weirdly configured projects. Unfortunately, I can't reproduce it with a unit test without doing some refactoring in that function.

2023-12-27 00:05 UTC, Geod24 commented
@gedaiu : Could you share the package recipe (and perhaps selections) of the involved packages ? I might be able to write the UT for you.

2023-12-27 11:07 UTC, Geod24 commented
Actually there is a very simple test here: https://github.com/dlang/dub/issues/2696
However I was looking at this code and there are more issues with it (namely subpackages would also trigger segv).

2023-12-28 16:24 UTC, Geod24 commented
Submitted a more complete fix with tests in #2762 . Thanks for your PR though @gedaiu , because it led me to find other bugs!

2023-12-28 16:24 UTC, closed without merging