Throw instead of assertion and better message
dlang/dub pull request #2972
Opened 2024-10-22 19:25 UTC by MrcSnm

The assertion crashed code-d and gave no information on what was wrong.

2024-10-22 19:41 UTC, Geod24 requested changes
What was the stack trace ? The error is in the calling code.

2024-10-22 19:59 UTC, MrcSnm commented
I didn't get any stack trace somehow (I had to run on debugger), but this is a minimal reproducible example:

[duberr.zip](https://github.com/user-attachments/files/17481422/duberr.zip)

2024-10-22 21:27 UTC, Geod24 commented
It's not handling the following propery:
```json
			"dependencies": {
				":version-a": "*"
			}
```
I think that's a limitation of the parser, will see if I can fix it properly.

2025-05-14 23:08 UTC, Geod24 commented
Closing in favor of the fix: #3028

2025-05-14 23:08 UTC, closed without merging